#!/bin/bash

local_dir="$(dirname $0)"
_dir=$(pwd)
cd $local_dir
    if [ -e firehose.pid ]; then
        kill $(cat firehose.pid)
        rm -rf firehose.pid
    fi
    bundle install --quiet
    bundle exec ruby data.rb >> firehose.log 2>&1 &
    echo "$!" >> firehose.pid
    echo "$(date) Drinking from the firehose successfully!" >> firehose.log
cd $_dir
