#!/bin/bash

local_dir="$(dirname $0)"
if [ -e local_dir/firehose.pid ]; then
    echo "Process seems to be running (pid file still exists). To be safe, run the stop script first."
else
    bundle install --quiet
    bundle exec ruby data.rb >> firehose.log 2>&1 &
    echo "$!" >> firehose.pid
    echo "$(date) Drinking from the firehose successfully!" >> firehose.log
fi
